#!/usr/bin/sh
output_file="home/jenci/fonts.nix"

names=(
	"Iosevka"
	"JetBrainsMono"
	"CommitMono"
)

echo "" >> "$output_file"
echo "# === Prefetched wallpaper hashes ===" >> "$output_file"

for name in "${names[@]}"; do
  url="https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/${name}.zip"
  hash=$(nix-prefetch-url "$url" 2>/dev/null)
  echo "{ url = \"$url\"; hash = \"$hash\"; }," >> "$output_file"
done
