themes:
  - name: "rose-pine-moon"
    colors:
      - "#181825"  # Base (dark background)
      - "#1E1E2E"  # Surface
      - "#313244"  # Overlay
      - "#45475A"  # Muted
      - "#585B70"  # Subtle
      - "#6C7086"  # Text
      - "#89B4FA"  # Love (accent)
      - "#F5C2E7"  # Gold (accent)
      - "#A6E3A1"  # Rose (accent)
      - "#94E2D5"  # Pine (accent)
      - "#F9E2AF"  # Foam (accent)
      - "#BAC2DE"  # Iris (accent)
      - "#CDD6F4"  # Highlight
      - "#F5E0DC"  # Highlight low
      - "#7F849C"  # Highlight med
      - "#9399B2"  # Highlight high
      - "#11111B"  # Base dark
      - "#A6ADC8"  # Subtle light
      - "#74C7EC"  # Sky
      - "#F38BA8"  # Pink
      - "#EBA0AC"  # Coral
      - "#FAB387"  # Peach
      - "#B4BEFE"  # Lavender
      - "#89DCEB"  # Cyan
      - "#CBA6F7"  # Violet
      - "#F2CDCD"  # Soft pink
