name: Zig CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Zig
        uses: marktiedemann/zig-action@v1
        with:
          version: 0.13.0

      - name: Build the project
        run: zig build

      - name: Run tests
        run: zig test

